### ISSUE TITLE
Update MUI css function and other deprecations

### ISSUE THREAD

**Issue by jeffvg** [brightlayer-ui/react-design-patterns#106]
#### Describe the bug
React design patterns repo and possibly other react blui projects have deprecation warnings and if updates are available proceed to use new functions

![image](https://user-images.githubusercontent.com/37150565/137504223-e2f39945-897b-4c6d-8cb4-5dfae082aa07.png)

#### What are the steps to reproduce?
1. Go to http://localhost:3000/status-list in mobile view on Fire Fox
2. Click on accordion
3. Material-ui css dep warning always present

**Comment by daileytj** [comment]
fixed
