### ISSUE TITLE
Failed prop type Material-UI: `overlap="circle"` was deprecated

### ISSUE THREAD

**Issue by jeffvg** [brightlayer-ui/react-design-patterns#158]
#### Describe the bug
When navigating to user menu in app bar http://localhost:3000/in-an-app-bar example noticed this deprecation
![image](https://user-images.githubusercontent.com/37150565/152211436-3937d7d9-e8d0-4d27-9554-f5549389d47f.png)

#### What are the steps to reproduce?
1. spin up react-design-patterns
2. Click on...http://localhost:3000/in-an-app-bar with dev tools open

**Comment by jeffvg** [comment]
verify this is fixed when MUIv5 is implemented

**Comment by daileytj** [comment]
Seems to be working fine post mui-v5 updates
