### ISSUE TITLE
Material-UI `fade` color utility was renamed to `alpha`

### ISSUE THREAD

**Issue by jeffvg** [brightlayer-ui/react-design-patterns#159]
#### Describe the bug
Navigating to http://localhost:3000/skeletons with dev tools open notification is displayed.
![image](https://user-images.githubusercontent.com/37150565/152212076-1441c0ed-b32f-41f7-ae98-24dc152ac218.png)

#### What is the expected behavior?
no warning
#### What are the steps to reproduce?
1. spin up react-design-patterns
2. Click on...http://localhost:3000/skeletons with dev tools open

looks like this will need changed in the react component library as well.

**Comment by jeffvg** [comment]
verify this is fixed once MUIv5 has been implemented

**Comment by bkarambe** [comment]
Seems it has already been fixed in MUI V5 migration.
Please refer the attached screen recording:

https://user-images.githubusercontent.com/25982779/209667403-f65dda57-1095-47ee-9141-e7cddb525f73.mov
