### ISSUE TITLE
Collapse Appbar Mouse Drag Scroll

### ISSUE THREAD

**Issue by emclaug2** [brightlayer-ui/react-design-patterns#37]
#### Describe the bug
App bar does not appear if I scroll using the mouse and side-bar on windows.

#### What is the expected behavior?
Toolbar should appear regardless of scroll source.

In the gif below I scroll the first time using a mouse-wheel.
The second time is using the side scroll bar.

#### Screenshots or links to minimum reproduction example
![circleasdgasdga](https://user-images.githubusercontent.com/6538289/92791835-06460300-f37b-11ea-8da7-ada69c2284e1.gif)

#### Environment

Windows, Chrome

**Comment by jeffvg** [comment]
yes this is making the cypress test scrollToView fail too.

**Comment by joebochill** [comment]
Is this an issue in the component or the demo?

**Comment by bkarambe** [comment]
It is working as expected.
